### ISSUE TITLE
锄大地的时候，进战斗，不能触发自动战斗

### ISSUE THREAD

**Issue by xxqq170** [DoctorReid/StarRailAutoProxy#100]
![Snipaste_2023-12-02_13-44-17](https://github.com/DoctorReid/StarRailAutoProxy/assets/115010355/d04eed6d-7b99-43c0-88c5-ed5acbcf6490)

鼠标始终在屏幕左上角和右下角狂点，咋整啊，大佬

**Comment by yinghaodang** [comment]
先按 f9 暂停运行，再按 f10 停止运行。
最后调整好窗口位置（不要有遮挡），重新点击“运行”按钮。
-------
感觉是一个bug，我明明开了自动战斗，但是老是弹出检测到未启动。再看看。

**Comment by xxqq170** [comment]
> 先按 f9 暂停运行，再按 f10 停止运行。 最后调整好窗口位置（不要有遮挡），重新点击“运行”按钮。
> 
> 感觉是一个bug，我明明开了自动战斗，但是老是弹出检测到未启动。再看看。

**Comment by DoctorReid** [comment]
@xxqq170 自动战斗的判断的确没做好，但是应该不影响使用吧

**Comment by xxqq170** [comment]
> 现在情况是你的游戏设置没有开启连续自动战斗，然后脚本没点击到自动战斗的按钮？
> 还是脚本不停在点自动战斗导致战斗卡住了？

啊，游戏设置里还有连续自动战斗的选项啊，抱歉大佬，刚玩没几天，不熟悉，那这样的话确实不影响了，我一直是手动点击自动战斗。然后在我没开连续自动战斗的情况下，脚本没点击到自动战斗，一直在屏幕左下角和左上角重复点击

**Comment by xxqq170** [comment]
不确定有没有在点击，开始战斗的时候，反正鼠标是大部分时间停留在屏幕左下角，就是uid这三个字母的位置，偶尔会跳到屏幕左上角

**Comment by xxqq170** [comment]
有一说一，大佬你这个工具真好用
