### ISSUE TITLE
锄大地的时候，进战斗，不能触发自动战斗 

### ISSUE THREAD

**Issue by xxqq170** [DoctorReid/StarRailAutoProxy#102]
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/115010355/10212252-2d82-4346-9fb3-c6bb79938439)
之前那个议题不小心给关了

**Comment by xxqq170** [comment]
1920*1080全屏幕

**Comment by DoctorReid** [comment]
关联 #100 待检查游戏设置未开启自动战斗时是否有问题

**Comment by DoctorReid** [comment]
检测自动战斗部分代码有bug 已修复。游戏中无设置自动战斗也能使用了
