### ISSUE TITLE
[锄大地] 部分锄地路线会卡在楼梯

### ISSUE THREAD

**Issue by lxb007981** [DoctorReid/StarRailAutoProxy#116]
多次出现问题的路线有

仙舟罗浮_廻星港_飞星小筑 会在(695, 310)附近楼梯处卡住
仙舟罗浮_太卜司_界寰阵 会在(797, 426)附近楼梯处卡住

有时候能自行脱困 有时候不能

我的网络延迟在220ms左右 也许和这个有关

**Comment by yinghaodang** [comment]
这是正常现象，这种情况除非进一步提升算法精度，不然很难避免。
卡住的话会有日志产生，在意漏怪的话，每天只要检查日志中"执行失败"这样的关键词，就能知道哪条路线执行失败了。
