### ISSUE TITLE
[Bug] 「結束後」設定不會儲存

### ISSUE THREAD

**Issue by seriaati** [DoctorReid/StarRailAutoProxy#141]
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/61446626/aee81208-9b13-49c6-b24a-16185d3b792c)
點擊「結束後」，選擇「關遊戲」，執行腳本，結束後遊戲沒關。
點擊「結束後」，選擇「關遊戲」，關閉自動代理器，打開自動代理器，設定變回「無」。

**Comment by DoctorReid** [comment]
关游戏我试了可以哦。这个设置暂时是不保存的，以后会考虑
