### ISSUE TITLE
模拟宇宙中莫名其妙的停止脚本，而且明明设定选的是毁灭或者欢愉命途，脚本总是选择繁育。

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/StarRailAutoProxy#164]
![无标题](https://github.com/DoctorReid/StarRailAutoProxy/assets/23742160/df39897d-7c05-4971-bf67-ff7bbac262cd)

**Comment by DoctorReid** [comment]
模拟宇宙等我今晚的新版本
