### ISSUE TITLE
global server 

### ISSUE THREAD

**Issue by ntuan14** [DoctorReid/StarRailAutoProxy#44]
Interesting but can it work in global server in the future ?

**Comment by DoctorReid** [comment]
There is a prepared module for version of other language, which just needs corresponding translation and test.
But it's not in short-term schedule, at least not in Nov. 2023

> Interesting but can it work in global server in the future ?

**Comment by DoctorReid** [comment]
#65 English version is on schedule now

**Comment by ntuan14** [comment]
tks u :3
