### ISSUE TITLE
作者大佬能不能加个自选地图 开始运行 

### ISSUE THREAD

**Issue by 1224910892** [DoctorReid/StarRailAutoProxy#56]

**Comment by 1224910892** [comment]
选任意一张地图 运行开始锄地 这样中途卡了 也不用从头跑

**Comment by DoctorReid** [comment]
> 选任意一张地图 运行开始锄地 这样中途卡了 也不用从头跑

脚本有运行记录，当天跑过的路线会自动跳过的，昨晚本地写完wiki还没有发上来，晚上下班回去再更新

**Comment by 1224910892** [comment]
还有 我刚刚运行过 跑到收容舱段 到 支援舱段 直接跳过支援舱段 不知道是不是识别不到还是什么 到雅利洛也是 中间都跳过好2 3个图 我设置是1920 1080 渲染0.6 光照最高 其他设置都是全部最低 或者关闭 我上传了log 你可以看看
[log.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13066509/log.txt)

**Comment by DoctorReid** [comment]
> 还有 我刚刚运行过 跑到收容舱段 到 支援舱段 直接跳过支援舱段 不知道是不是识别不到还是什么 到雅利洛也是 中间都跳过好2 3个图 我设置是1920 1080 渲染0.6 光照最高 其他设置都是全部最低 或者关闭 我上传了log 你可以看看 [log.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13066509/log.txt)

感谢测试和提供日志！

从日志上看，有一些跳过是因为路线之前已经运行过了，另外的都是因为**OCR识别中文**失败，导致跳过路线，这块看看能不能开高一点配置。

之前测试都是在最高画质下运行，后续我再做一下低画质的测试和调整。

**Comment by 1224910892** [comment]
好得

**Comment by 1224910892** [comment]
嗯

**Comment by 1224910892** [comment]
[log.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13110476/log.txt)
![E4~03 X7MGZT0C S}H_4)GJ](https://github.com/DoctorReid/StarRailAutoProxy/assets/103303404/142a9e09-4614-4ff6-9bef-2b8518b015d2)
我不知道是不是我的问题 我按昨天的方法用 直接用不了现在 031 032 都不能用  按校准 锄地 都没反应 显示个加载成功 就是不动

**Comment by DoctorReid** [comment]
> [log.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13110476/log.txt) ![E4~03 X7MGZT0C S}H_4)GJ](https://user-images.githubusercontent.com/103303404/277542052-142a9e09-4614-4ff6-9bef-2b8518b015d2.png) 我不知道是不是我的问题 我按昨天的方法用 直接用不了现在 031 032 都不能用 按校准 锄地 都没反应 显示个加载成功 就是不动

看上去是让游戏窗口恢复到前台失败了，可以尝试**不要最小化游戏窗口**

**Comment by 1224910892** [comment]
我屏幕是1920*1080的 
![FYVL%AKBNQ (6Y)HQCLDDK4](https://github.com/DoctorReid/StarRailAutoProxy/assets/103303404/c8de80fb-7b4d-4134-a2c9-7cf55eaaa773)
一样是同样问题 我是全屏幕的 游戏也在前天 后台按F9 也是无反应 我是管理员模式运行的

**Comment by 1224910892** [comment]
![6(T} YCAOB)WXBMTKN2WEZA](https://github.com/DoctorReid/StarRailAutoProxy/assets/103303404/485472a5-429f-447e-80e2-f69f4ff208f6)
按了F9 游戏就闪一下 但是他就是不切过去 我哪怕是在 游戏前台按F9也是如此

**Comment by 1224910892** [comment]
![%{93{YZ33F8~OGZ%9PTD6XI](https://github.com/DoctorReid/StarRailAutoProxy/assets/103303404/5cebfd37-9163-4ddf-a262-c6b3b915d820)

**Comment by DoctorReid** [comment]
> 我屏幕是1920*1080的 ![FYVL%AKBNQ (6Y)HQCLDDK4](https://user-images.githubusercontent.com/103303404/277638218-c8de80fb-7b4d-4134-a2c9-7cf55eaaa773.png) 一样是同样问题 我是全屏幕的 游戏也在前天 后台按F9 也是无反应 我是管理员模式运行的

昨晚我试了下全屏，没问题。如果console中报错还是之前那个的话，暂时没想到什么原因了。周末有空可以加你QQ看看

**Comment by SlowpokeFisher** [comment]
> [log.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13110476/log.txt) ![E4~03 X7MGZT0C S}H_4)GJ](https://user-images.githubusercontent.com/103303404/277542052-142a9e09-4614-4ff6-9bef-2b8518b015d2.png) 我不知道是不是我的问题 我按昨天的方法用 直接用不了现在 031 032 都不能用 按校准 锄地 都没反应 显示个加载成功 就是不动

我这边遇到了一样的问题，点校准没有反应。开始运行时并没有将游戏窗口最小化。用的是v0.3.3 release打包好的，管理员权限启动。
<img width="1920" alt="屏幕截图 2023-10-24 202438" src="https://github.com/DoctorReid/StarRailAutoProxy/assets/35548827/819cb341-205b-4076-9ffd-0f7aa6cfa974">

**Comment by 1224910892** [comment]
是吧

**Comment by SlowpokeFisher** [comment]
@1224910892 
我这边参考 https://github.com/asweigart/PyGetWindow/issues/16#issuecomment-1110207862
把 https://github.com/DoctorReid/StarRailAutoProxy/blob/main/src/sr/win.py#L35改成

```
    def active(self):
        """
        显示并激活当前窗口
        :return:
        """
        self.win.show()
        try:
            self.win.activate()
        except:
            self.win.minimize()
            self.win.restore()
```
至少就不会卡在这里了。感觉是`pygetwindow`有点问题。

**Comment by DoctorReid** [comment]
> @1224910892 我这边参考 [asweigart/PyGetWindow#16 (comment)](https://github.com/asweigart/PyGetWindow/issues/16#issuecomment-1110207862) 把 https://github.com/DoctorReid/StarRailAutoProxy/blob/main/src/sr/win.py#L35 改成
> 
> ```
>     def active(self):
>         """
>         显示并激活当前窗口
>         :return:
>         """
>         self.win.show()
>         try:
>             self.win.activate()
>         except:
>             self.win.minimize()
>             self.win.restore()
> ```
> 
> 至少就不会卡在这里了。感觉是`pygetwindow`有点问题。

会不会是```self.win.activate()```前调用一下 ```self.win.restore()``` 就够了，我之前只改了```win_utils.py```里，忘记改```win.py```，有空的话能帮忙试试吗

**Comment by 1224910892** [comment]
但是我不懂改代码啊 可以加我QQ 553747233 给你试没问题

**Comment by DoctorReid** [comment]
> 但是我不懂改代码啊 可以加我QQ 553747233 给你试没问题

我是说另一个的兄弟

**Comment by 1224910892** [comment]
好得 哈哈哈

**Comment by SlowpokeFisher** [comment]
> 会不会是`self.win.activate()`前调用一下 `self.win.restore()` 就够了，我之前只改了`win_utils.py`里，忘记改`win.py`，有空的话能帮忙试试吗

改成
```
        if not self.is_active():
            self.win.restore()
            self.win.activate()
```

还是一样

```
Exception in thread Thread-48 (run_app):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\src\gui\calibrator_view.py", line 15, in run_app
    app.execute()
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\src\sr\app\__init__.py", line 20, in execute
    if not self.ctx.start_running():
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\src\sr\context.py", line 61, in start_running
    self.controller.init()
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\src\sr\control\pc_controller.py", line 32, in init
    self.win.active()
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\src\sr\win.py", line 43, in active
    self.win.activate()
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\.env\venv\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
  File "C:\Users\wsqua\Documents\dev\StarRailAutoProxy\.env\venv\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 0 - 操作成功完成。
```

**Comment by DoctorReid** [comment]
> 好得 哈哈哈

@1224910892 试试 v0.3.4 应该可以了

**Comment by 1224910892** [comment]
@DoctorReid 好 我现在试试

**Comment by 1224910892** [comment]
@DoctorReid 校准不能百分百成功  我已经提高了画质 全部最高 依然是不能成功 我前面多试了几次 倒是成功一次 后面我再跑跑看
[log.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13172895/log.txt)

**Comment by SlowpokeFisher** [comment]
其实我有点好奇校准用的传送点为啥从注释里提到的P01_R02_SP02 （基座舱段接待中心）改成现在的P01_R04_SP03（电力室）了？最新版我还没机会试，不过昨天0.3.3的时候电力室我就没校准成功过，接待中心还是很稳的

**Comment by 1224910892** [comment]
@ @DoctorReid 那个校准 我要把画质提到最高 我才能成功 我校准之后 把画质调到最低 渲染0.6 其他全关 光照最高 锄是锄完了 漏了一些怪 还挺多

**Comment by 1224910892** [comment]
@DoctorReid 我总结了一些路线优化 你可以参考一下 把我今天漏得怪得 我自己也看了一遍 确实会漏 我对路线提供一些建议
[路线优化建议.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13174014/default.txt)
改完应该是一个不会漏了

**Comment by DoctorReid** [comment]
> @DoctorReid 我总结了一些路线优化 你可以参考一下 把我今天漏得怪得 我自己也看了一遍 确实会漏 我对路线提供一些建议 [路线优化建议.txt](https://github.com/DoctorReid/StarRailAutoProxy/files/13174014/default.txt) 改完应该是一个不会漏了

感谢提供~我回去看看

程序中有```锄地路线录制```工具，你可以尝试使用编辑路线测试。

**Comment by DoctorReid** [comment]
> 其实我有点好奇校准用的传送点为啥从注释里提到的P01_R02_SP02 （基座舱段接待中心）改成现在的P01_R04_SP03（电力室）了？最新版我还没机会试，不过昨天0.3.3的时候电力室我就没校准成功过，接待中心还是很稳的

这个纯属我自己手抖了。。。。回头改一下

**Comment by 1224910892** [comment]
@DoctorReid 哦 那个我会用 我就是懒 嘿嘿

**Comment by DoctorReid** [comment]
@1224910892 @SlowpokeFisher 两位提出的问题应该都修复了，如果没问题一天后就会关闭这个issue。后续可以提其他issue或者加QQ群```743525216```联系

**Comment by 1224910892** [comment]
@DoctorReid 作者你修了路线没 我昨晚调整了 今天早上跑了 没问题

**Comment by 1224910892** [comment]
@DoctorReid 我刚刚才发现你上了4.0 好吧 你调整那应该是没问题了 我那个也没什么问题 我还想发给你

**Comment by DoctorReid** [comment]
> @DoctorReid 我刚刚才发现你上了4.0 好吧 你调整那应该是没问题了 我那个也没什么问题 我还想发给你

改了但还没完整测过，因为白天把怪刷了，晚上回去怪不全。路线上给你加了署名，都是数字，要改的说一声

**Comment by 1224910892** [comment]
@DoctorReid 我加了你得QQ群还没通过  名字改成 龙女姬 谢谢大佬 进QQ群方便点 我自己调整得是没问题了
