### ISSUE TITLE
無法啟動校正

### ISSUE THREAD

**Issue by johnson50313** [DoctorReid/StarRailAutoProxy#67]
[LOG截圖](https://imgur.com/a/OnMJy2a)

**Comment by DoctorReid** [comment]
> [LOG截圖](https://imgur.com/a/OnMJy2a)

公司网络被墙看不到图，可以尝试上传txt文件，或者加入QQ群 ```743525216``` 看看。

看你写的标题用的繁体中文，目前是不支持繁体的，可以尝试用简体中文版本试试

**Comment by DoctorReid** [comment]
> 已經設定簡體中文
> 
> ![image](https://user-images.githubusercontent.com/118783940/278571064-8b4a1b02-3791-4982-919c-b0da7cb778d2.png)

看上去是没有成功切换到游戏窗口，可试试试用管理员权限运行

**Comment by johnson50313** [comment]
管理员权限运行，可正常使用
測試中 謝謝
