### ISSUE TITLE
校准失败

### ISSUE THREAD

**Issue by 2572190756** [DoctorReid/StarRailAutoProxy#79]
在 C:\Users\LENOVO\Downloads\StarRailAutoProxy-v0.5.3\dist\StarRailAutoProxy 管理员运行  游戏1920*1080 窗口模式  启动校准 一直失败  打开手机后 鼠标移动到左下角 然后退出手机界面了
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/74443980/c19398b9-c74f-461c-996a-43609bf33996)

下面是 cmd 的显示
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
2023-10-31 23:15:44.7884558 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1987 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x00000171FBEB13A0>.
  warnings.warn(
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x00000171FBEB23E0>.
  warnings.warn(
[INFO 2023-10-31 23:16:49,462 execute:15] 加载工具中
[INFO 2023-10-31 23:16:49,462 init_image_matcher:129] 加载图片匹配器完毕
[INFO 2023-10-31 23:16:49,690 init_ocr_matcher:137] 加载OCR识别器完毕
[INFO 2023-10-31 23:16:49,693 init_controller:121] 加载游戏控制器完毕
[INFO 2023-10-31 23:16:49,694 execute:19] 加载工具完毕
[INFO 2023-10-31 23:16:50,385 _check_mini_map_pos:35] [小地图定位校准] 开始
[INFO 2023-10-31 23:16:50,450 run:33] 准备传送 空间站黑塔 基座舱段 接待中心
[INFO 2023-10-31 23:16:50,679 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:50,680 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:52,004 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:52,005 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:53,372 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:53,375 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:54,679 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:54,680 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:55,997 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:55,999 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:57,303 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:57,307 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:58,610 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:58,612 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:16:59,917 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:16:59,919 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:01,256 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:01,258 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:02,690 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:02,693 run:43] 尝试返回上级菜单
[ERROR 2023-10-31 23:17:03,798 _check_mini_map_pos:40] 传送到 基座舱段 接待中心 失败 小地图定位校准 失败
[INFO 2023-10-31 23:17:03,799 _check_turning_rate:64] [转向校准] 开始
[INFO 2023-10-31 23:17:03,845 run:33] 准备传送 空间站黑塔 主控舱段 黑塔的办公室
[INFO 2023-10-31 23:17:04,069 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:04,071 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:05,384 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:05,385 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:06,690 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:06,691 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:08,005 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:08,007 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:09,319 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:09,321 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:10,634 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:10,637 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:11,955 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:11,959 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:13,279 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:13,281 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:14,587 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:14,594 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:17:15,899 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:17:15,901 run:43] 尝试返回上级菜单
[ERROR 2023-10-31 23:17:17,006 _check_turning_rate:69] 传送到 主控舱段 黑塔的办公室 失败 转向校准 失败
[INFO 2023-10-31 23:17:17,008 stop_running:70] 停止运行
[INFO 2023-10-31 23:17:17,009 switch:85] 暂停运行
[INFO 2023-10-31 23:18:10,989 execute:15] 加载工具中
[INFO 2023-10-31 23:18:10,991 init_image_matcher:129] 加载图片匹配器完毕
[INFO 2023-10-31 23:18:10,992 init_ocr_matcher:137] 加载OCR识别器完毕
[INFO 2023-10-31 23:18:10,995 init_controller:121] 加载游戏控制器完毕
[INFO 2023-10-31 23:18:10,996 execute:19] 加载工具完毕
[INFO 2023-10-31 23:18:11,499 load_all_route_id:402] 最终加载 43 条线路 过滤已完成 0 条 使用名单 None
[INFO 2023-10-31 23:18:11,505 run_one_route:242] 准备执行线路 空间站黑塔_基座舱段_监控室
[INFO 2023-10-31 23:18:11,506 run_one_route:244] 感谢以下人员提供本路线 ['DoctorReid']
[INFO 2023-10-31 23:18:11,507 run:33] 准备传送 空间站黑塔 基座舱段 监控室
[INFO 2023-10-31 23:18:12,234 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:12,236 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:13,539 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:13,540 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:14,849 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:14,852 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:16,177 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:16,180 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:17,477 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:17,478 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:18,774 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:18,776 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:20,080 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:20,084 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:21,380 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:21,382 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:22,685 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:22,687 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:23,991 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:23,993 run:43] 尝试返回上级菜单
[ERROR 2023-10-31 23:18:25,097 run_one_route:247] 传送失败 即将跳过本次路线 空间站黑塔_基座舱段_监控室
[INFO 2023-10-31 23:18:25,105 run_one_route:242] 准备执行线路 空间站黑塔_收容舱段_毁灭之蕾
[INFO 2023-10-31 23:18:25,117 run_one_route:244] 感谢以下人员提供本路线 ['DoctorReid']
[INFO 2023-10-31 23:18:25,204 run:33] 准备传送 空间站黑塔 收容舱段 毁灭之蕾
[INFO 2023-10-31 23:18:25,404 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:25,410 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:26,719 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:26,722 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:28,041 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:28,043 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:29,351 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:29,354 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:30,681 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:30,684 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:31,985 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:31,989 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:33,307 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:33,311 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:34,648 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:34,650 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:18:35,857 stop_running:70] 停止运行
[INFO 2023-10-31 23:18:35,910 switch:85] 暂停运行
[INFO 2023-10-31 23:18:35,952 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:18:35,955 run:43] 尝试返回上级菜单
[ERROR 2023-10-31 23:18:37,062 run_one_route:247] 传送失败 即将跳过本次路线 空间站黑塔_收容舱段_毁灭之蕾
[INFO 2023-10-31 23:18:37,063 stop_running:70] 停止运行
[INFO 2023-10-31 23:19:17,567 execute:15] 加载工具中
[INFO 2023-10-31 23:19:17,569 init_image_matcher:129] 加载图片匹配器完毕
[INFO 2023-10-31 23:19:17,572 init_ocr_matcher:137] 加载OCR识别器完毕
[INFO 2023-10-31 23:19:17,575 init_controller:121] 加载游戏控制器完毕
[INFO 2023-10-31 23:19:17,580 execute:19] 加载工具完毕
[INFO 2023-10-31 23:19:18,082 _check_mini_map_pos:35] [小地图定位校准] 开始
[INFO 2023-10-31 23:19:18,085 run:33] 准备传送 空间站黑塔 基座舱段 接待中心
[INFO 2023-10-31 23:19:18,311 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:18,318 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:19,633 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:19,639 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:20,966 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:20,975 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:22,279 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:22,282 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:23,585 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:23,588 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:24,882 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:24,889 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:26,204 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:26,207 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:27,509 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:27,513 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:28,822 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:28,826 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:30,113 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:30,116 run:43] 尝试返回上级菜单
[ERROR 2023-10-31 23:19:31,222 _check_mini_map_pos:40] 传送到 基座舱段 接待中心 失败 小地图定位校准 失败
[INFO 2023-10-31 23:19:31,226 _check_turning_rate:64] [转向校准] 开始
[INFO 2023-10-31 23:19:31,228 run:33] 准备传送 空间站黑塔 主控舱段 黑塔的办公室
[INFO 2023-10-31 23:19:31,419 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:31,424 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:32,730 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:32,735 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:34,044 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:34,048 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:35,341 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:35,344 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:36,635 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:36,639 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:37,940 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:37,946 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:39,238 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:39,241 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:40,540 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:40,545 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:41,860 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:41,864 run:43] 尝试返回上级菜单
[INFO 2023-10-31 23:19:43,168 run:38] 当前大地图所处星球 None
[INFO 2023-10-31 23:19:43,173 run:43] 尝试返回上级菜单
[ERROR 2023-10-31 23:19:44,287 _check_turning_rate:69] 传送到 主控舱段 黑塔的办公室 失败 转向校准 失败
[INFO 2023-10-31 23:19:44,290 stop_running:70] 停止运行
[INFO 2023-10-31 23:19:44,293 switch:85] 暂停运行
[INFO 2023-10-31 23:20:10,576 load_all_route_id:402] 最终加载 43 条线路 过滤已完成 0 条 使用名单 None
[INFO 2023-10-31 23:20:11,688 load_all_route_id:402] 最终加载 43 条线路 过滤已完成 0 条 使用名单 None

**Comment by DoctorReid** [comment]
@2572190756 暂时没看出来为什么，可以试试0.5.4版本，或者加QQ详细看看
