### ISSUE TITLE
部分地图的yml文件存在tp名称与预设TransportPoint.cn不匹配

### ISSUE THREAD

**Issue by jiangcy1994** [DoctorReid/StarRailAutoProxy#92]
随着更新`a4e48b0333459449aaf3e3bad5c8d156cb84d1bc`中文件`src\sr\const\map_const.py`等文件中以下相关内容的更新：

- `*拟造花萼赤`
- `*拟造花萼金`
- `*侵蚀隧洞`
- '*凝滞虚影'

文件`config\world_patrol\*\*.yml`内部分文件tp可能需要更改

**Comment by DoctorReid** [comment]
@jiangcy1994 感谢提出 已经修复
