### ISSUE TITLE
提几个使用中遇到的一些问题

### ISSUE THREAD

**Issue by chen8945** [DoctorReid/StarRailAutoProxy#93]
### 白名单相关
- 白名单编辑界面地图没有滚动条，一些比较大的图把程序全屏也无法显示完整
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/44148812/c418c7ed-7cf1-4f99-b754-e224a10d97f0)
- 添加白名单后名单列表依然显示空白，需要重启一次应用后才会显示，黑名单亦是如此
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/44148812/65970bcd-0876-4803-9737-158891302bab)
- 添加黑白名单的时候增加多选功能，例如复选框或者像 Windows 系统这样可以通过按住 SHIFT 和 CTRL 键来进行多选
- 增加名单自定义命名功能，方便快速识别名单作用

### 程序相关
- 在使用源码运行的时候，需要设置 `PYTHONPATH` 变量为 `src` 目录，才能正常启动
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/44148812/eb7e7c76-a585-4428-a81c-b61bdd2fcd11)
否则就会如下图一样识别不到 `src` 目录中的 `basic` 包，虽然可以通过 bat 脚本解决此问题，但还是希望能尽量稍微优化一下，简化启动步骤
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/44148812/bb73ce95-dc1f-4867-8490-bac5d089d77b)

**Comment by DoctorReid** [comment]
这个功能本来没想到有人会用，所以修改优先级可能比较低
- 显示地图的滚动条可以加
- 名单编辑后重新加载可以优化
- 多选应该不行，因为要显示路线才能知道自己选的是什么
- 自定义命名可以
- 源码启动问题属于个人开发环境设置，不打算更改

**Comment by chen8945** [comment]
> * 多选应该不行，因为要显示路线才能知道自己选的是什么

- 关于多选这个，目前地图还比较少可能还好，随着更新后面地图会越来越多，如果要设置的图比较多，还得先一个一个点开列表，然后选择路线，再添加，无疑是徒增烦恼，而且大多数人应该只是单纯的想锄大地，并不是想查看路线，确实有查看路线需求的人可以自行点击地图名字查看，或者在路线绘制里查看
- 还有一个点是在选择路线这个，可以和路线绘制里一样，分为星球和区域两个选择项，后续地图增多在选择的时候也会更加直观
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/44148812/7c2c8ca4-d2b4-43f3-b42a-f6565202cc64)
- 在上面这条的基础上，可以新增一个小功能，例如我星球选择仙舟罗浮，后续选项为空，点击添加后就直接将仙舟罗浮所有地图添加进入名单

**Comment by DoctorReid** [comment]
- 地图显示部分增加滚动条
- 增加名单名称
- 名单可以直接添加整个星球或者整个区域的路线
- 名单保存后界面上会刷新显示
