### ISSUE TITLE
使用体验

### ISSUE THREAD

**Issue by yinghaodang** [DoctorReid/StarRailAutoProxy#95]
基于坐标移动的锄大地策略确实比基于按键的策略更优。后续要好好学习一下大佬的代码。
体验了两天，希望下面几点可以优化一下。

1. 可以自由选择从哪条路线开始锄大地。可以自由调整锄大地的线路。也就是白名单这个功能。
    用户可以将自己画的路线添加到队列里面，然后执行队列。
2. 绘制锄大地，这个功能非常强，，，可以不进游戏就绘制路线图。但是似乎缺一个新建的按钮吧...目前可以先清空路线，然后将重新绘 
    制的数据手动保存到对应文件夹下，只要不点保存就不会修改原数据。

----------------
其余功能目前需求不大，估计再玩一两个月说不定就用得上了。

测试了"开拓力"这个功能
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/49315320/45f27fa6-1e23-4c18-b32f-3f17c05c2934)
本轮完成这个参数默认是0，我曾成功设置成2过，然后在拟造花萼的时候会选择打两个波次。但是，有时候会无法设置。
后面的参数计划次数也会失效，会不断地进行直到体力用完。

还有在匹配地图的时候似乎没有加上将地图缩小到最小化的操作，有时候地图匹配会出错。
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/49315320/8541da11-b956-4394-b8ca-ed393d6bc224)
日志还报了这样的assert，不知道是不是我的操作有问题。

**Comment by yinghaodang** [comment]
补充两点
1. 刷完一轮拟造花萼，重复刷会重新定位星球，可以改成再次挑战，算是一个小优化点。
2. 保存到本地的日志似乎乱码了，是UTF-8吗

**Comment by DoctorReid** [comment]
感谢提出，这周工作较忙没回复到。

1. 白名单功能本来只是早期一个实验功能，后续没迭代了。因为有保存记录可以随时停止随时再重跑，整体运行时间也能在2小时内，所以感觉选择路线没有太大必要。后续我会再考虑下这个功能迭代。
2. 不先选择路线，直接选择星球-区域-传送点，就可以绘制新路线，然后点击保存即可。路线也可以选择删除，变相补充了一点路线名单功能。
3. 【本轮完成】不能大于【计划次数】，脚本中强制设置了，所以才有更改不了的情况。
4. 日志的assert问题已知，稍后修复
5. 重复刷会重新定位星球，稍后优化 #97 
6. 日志乱码问题已知，稍后修复
